export const LOAD_MESSAGE_CONVERSATIONS = 'LOAD_MESSAGE_CONVERSATIONS';
export const MESSAGE_CONVERSATIONS_LOAD_SUCCESS = 'MESSAGE_CONVERSATIONS_LOAD_SUCCESS';
export const MESSAGE_CONVERSATIONS_LOAD_ERROR = 'MESSAGE_CONVERSATIONS_LOAD_ERROR';

export const MESSAGE_CONVERSATIONS_LOAD_FINISHED = 'MESSAGE_CONVERSATIONS_LOAD_FINISHED';

export const MARK_MESSAGE_CONVERSATIONS_READ = 'MARK_MESSAGE_CONVERSATIONS_READ';
export const MARK_MESSAGE_CONVERSATIONS_READ_ERROR = 'MARK_MESSAGE_CONVERSATIONS_READ_ERROR';

export const MARK_MESSAGE_CONVERSATIONS_UNREAD = 'MARK_MESSAGE_CONVERSATIONS_UNREAD';
export const MARK_MESSAGE_CONVERSATIONS_UNREAD_ERROR = 'MARK_MESSAGE_CONVERSATIONS_UNREAD_ERROR';

/* Recipient actions */
export const RECIPIENT_SEARCH = 'RECIPIENT_SEARCH';
export const RECIPIENT_SEARCH_SUCCESS = 'RECIPIENT_SEARCH_SUCCESS';
export const RECIPIENT_SEARCH_ERROR = 'RECIPIENT_SEARCH_ERROR';