// This file is autogenerated by d2-i18n-generate

import i18n from 'd2-i18n';
import moment from 'moment';

import enTranslations from './en/translations.json';

const namespace = 'messaging-app';
moment.locale('en');

i18n.addResources('en', namespace, enTranslations);

i18n.setDefaultNamespace(namespace);
i18n.changeLanguage('en');

export default i18n;
