export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS'
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR'

export const LOAD_MESSAGE_CONVERSATIONS = 'LOAD_MESSAGE_CONVERSATIONS'
export const LOAD_MORE_MESSAGE_CONVERSATIONS = 'LOAD_MORE_MESSAGE_CONVERSATIONS'
export const MESSAGE_CONVERSATIONS_LOAD_SUCCESS =
    'MESSAGE_CONVERSATIONS_LOAD_SUCCESS'
export const MESSAGE_CONVERSATIONS_LOAD_ERROR =
    'MESSAGE_CONVERSATIONS_LOAD_ERROR'

export const DELETE_MESSAGE_CONVERSATIONS = 'DELETE_MESSAGE_CONVERSATIONS'
export const MESSAGE_CONVERSATIONS_DELETE_SUCCESS =
    'MESSAGE_CONVERSATIONS_DELETE_SUCCESS'
export const MESSAGE_CONVERSATIONS_DELETE_ERROR =
    'MESSAGE_CONVERSATIONS_DELETE_ERROR'

export const UPDATE_MESSAGE_CONVERSATIONS = 'UPDATE_MESSAGE_CONVERSATIONS'
export const MESSAGE_CONVERSATION_UPDATE_SUCCESS =
    'MESSAGE_CONVERSATION_UPDATE_SUCCESS'
export const MESSAGE_CONVERSATION_UPDATE_ERROR =
    'MESSAGE_CONVERSATION_UPDATE_ERROR'

export const MARK_MESSAGE_CONVERSATIONS = 'MARK_MESSAGE_CONVERSATIONS'
export const MARK_MESSAGE_CONVERSATIONS_SUCCESS =
    'MARK_MESSAGE_CONVERSATIONS_SUCCESS'
export const MARK_MESSAGE_CONVERSATIONS_ERROR =
    'MARK_MESSAGE_CONVERSATIONS_ERROR'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR'

export const SEND_FEEDBACK_MESSAGE = 'SEND_FEEDBACK_MESSAGE'

export const REPLY_MESSAGE = 'REPLY_MESSAGE'
export const REPLY_MESSAGE_SUCCESS = 'REPLY_MESSAGE_SUCCESS'
export const REPLY_MESSAGE_ERROR = 'REPLY_MESSAGE_ERROR'

export const SET_FILTER = 'SET_FILTER'
export const DISPLAY_SNACK_MESSAGE = 'DISPLAY_SNACK_MESSAGE;'
export const CLEAR_SNACK_MESSAGE = 'CLEAR_SNACK_MESSAGE'

export const SET_CHECKED = 'SET_CHECKED'
export const SET_ALL_CHECKED = 'SET_ALL_CHECKED'

export const CLEAR_CHECKED = 'CLEAR_CHECKED'
export const SET_SELECTED_MESSAGE_TYPE = 'SET_SELECTED_MESSAGE_TYPE'

export const CLEAR_SELECTED_MESSAGE_CONVERSATION =
    'CLEAR_SELECTED_MESSAGE_CONVERSATION'
export const SET_SELECTED_MESSAGE_CONVERSATION =
    'SET_SELECTED_MESSAGE_CONVERSATION'
export const SET_SELECTED_MESSAGE_CONVERSATION_SUCCESS =
    'SET_SELECTED_MESSAGE_CONVERSATION_SUCCESS'
export const SET_SELECTED_MESSAGE_CONVERSATION_ERROR =
    'SET_SELECTED_MESSAGE_CONVERSATION_ERROR'

export const UPDATE_INPUT_FIELDS = 'UPDATE_INPUT_FIELDS'

export const SET_IN_FEEDBACK_RECIPIENT_GROUP = 'SET_IN_FEEDBACK_RECIPIENT_GROUP'

export const SET_DISPLAY_TIME_DIFF = 'SET_DISPLAY_TIME_DIFF'
export const SET_DISPLAY_TIME_DIFF_SUCCESS = 'SET_DISPLAY_TIME_DIFF_SUCCESS'
export const SET_DISPLAY_TIME_DIFF_ERROR = 'SET_DISPLAY_TIME_DIFF_ERROR'

/* Recipient actions */
export const RECIPIENT_SEARCH = 'RECIPIENT_SEARCH'
export const RECIPIENT_SEARCH_SUCCESS = 'RECIPIENT_SEARCH_SUCCESS'
export const RECIPIENT_SEARCH_ERROR = 'RECIPIENT_SEARCH_ERROR'

export const ADD_RECIPIENTS = 'ADD_RECIPIENTS'
export const ADD_RECIPIENTS_SUCCESS = 'ADD_RECIPIENTS_SUCCESS'
export const ADD_RECIPIENTS_ERROR = 'ADD_RECIPIENTS_ERROR'
export const ADD_RECIPIENT_BY_ID_SUCCESS = 'ADD_RECIPIENT_BY_ID_SUCCESS'

/* Attachments */
export const ADD_ATTACHMENT = 'ADD_ATTACHMENT'
export const ADD_ATTACHMENT_SUCCESS = 'ADD_ATTACHMENT_SUCCESS'
export const ADD_ATTACHMENT_ERROR = 'ADD_ATTACHMENT_ERROR'

export const DOWNLOAD_ATTACHMENT = 'DOWNLOAD_ATTACHMENT'
export const DOWNLOAD_ATTACHMENT_SUCCESS = 'DOWNLOAD_ATTACHMENT_SUCCESS'
export const DOWNLOAD_ATTACHMENT_ERROR = 'DOWNLOAD_ATTACHMENT_ERROR'

export const REMOVE_ATTACHMENT = 'REMOVE_ATTACHMENT'

export const CLEAR_ATTACHMENTS = 'CLEAR_ATTACHMENTS'
export const CANCEL_ATTACHMENT = 'CANCEL_ATTACHMENT'

/* DHIS2 CORE VERSION */
export const SET_DHIS2_CORE_VERSION = 'SET_DHIS2_CORE_VERSION'
